// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalExpenseTracker.Data;

#nullable disable

namespace PersonalExpenseTracker.Migrations
{
    [DbContext(typeof(PersonalExpenseDbContext))]
    [Migration("20251124145755_Guid id added with some data seeding")]
    partial class Guididaddedwithsomedataseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalExpenseTracker.Models.Domain.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f94c2c07-9f92-4c21-9cb8-df1e0227d333"),
                            Amount = 2500.75m,
                            Date = new DateTime(2025, 11, 21, 14, 57, 53, 526, DateTimeKind.Utc).AddTicks(9893),
                            Notes = "Bought fruits, vegetables, snacks",
                            Title = "Grocery Shopping",
                            UserId = new Guid("c6b7c56f-1c72-4c2e-9c11-5cdd7d00c111")
                        },
                        new
                        {
                            Id = new Guid("ab7bb8f4-950e-4c84-b6d7-214a96ac3333"),
                            Amount = 5200.00m,
                            Date = new DateTime(2025, 11, 23, 14, 57, 53, 526, DateTimeKind.Utc).AddTicks(9904),
                            Notes = "Car petrol full tank",
                            Title = "Fuel Refill",
                            UserId = new Guid("c6b7c56f-1c72-4c2e-9c11-5cdd7d00c111")
                        },
                        new
                        {
                            Id = new Guid("d39afe32-a4f7-4d53-9668-0f0726c44444"),
                            Amount = 2500.00m,
                            Date = new DateTime(2025, 11, 19, 14, 57, 53, 526, DateTimeKind.Utc).AddTicks(9906),
                            Notes = "PTCL monthly bill",
                            Title = "Internet Bill",
                            UserId = new Guid("52a6240b-0f04-4be8-b54a-d1f6c6e05522")
                        });
                });

            modelBuilder.Entity("PersonalExpenseTracker.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6b7c56f-1c72-4c2e-9c11-5cdd7d00c111"),
                            CreatedAt = new DateTime(2025, 11, 24, 14, 57, 53, 526, DateTimeKind.Utc).AddTicks(9833),
                            Email = "ahmad@example.com",
                            Name = "Ahmad Raza",
                            Password = "123456"
                        },
                        new
                        {
                            Id = new Guid("52a6240b-0f04-4be8-b54a-d1f6c6e05522"),
                            CreatedAt = new DateTime(2025, 11, 24, 14, 57, 53, 526, DateTimeKind.Utc).AddTicks(9842),
                            Email = "ali@example.com",
                            Name = "Ali Khan",
                            Password = "password123"
                        });
                });

            modelBuilder.Entity("PersonalExpenseTracker.Models.Domain.Expense", b =>
                {
                    b.HasOne("PersonalExpenseTracker.Models.Domain.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalExpenseTracker.Models.Domain.User", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
