// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalExpenseTracker.Data;

#nullable disable

namespace PersonalExpenseTracker.Migrations
{
    [DbContext(typeof(PersonalExpenseDbContext))]
    partial class PersonalExpenseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalExpenseTracker.Models.Domain.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1500.50m,
                            Date = new DateTime(2025, 11, 19, 20, 19, 12, 776, DateTimeKind.Utc).AddTicks(3416),
                            Notes = "Bought vegetables and snacks",
                            Title = "Grocery Shopping",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 500m,
                            Date = new DateTime(2025, 11, 20, 20, 19, 12, 776, DateTimeKind.Utc).AddTicks(3427),
                            Notes = "Jazz monthly bundle",
                            Title = "Mobile Recharge",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("PersonalExpenseTracker.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 21, 20, 19, 12, 776, DateTimeKind.Utc).AddTicks(3249),
                            Email = "test@example.com",
                            Name = "Test User",
                            Password = "hashedpassword123"
                        });
                });

            modelBuilder.Entity("PersonalExpenseTracker.Models.Domain.Expense", b =>
                {
                    b.HasOne("PersonalExpenseTracker.Models.Domain.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalExpenseTracker.Models.Domain.User", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
